### ISSUE TITLE
a blog for multisig account using online toolkit

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#17]

**Comment by Yeonju-Kim** [comment]
Korean version: https://medium.com/klaytn-kr/%ED%81%B4%EB%A0%88%EC%9D%B4%ED%8A%BC-%EC%98%A8%EB%9D%BC%EC%9D%B8-%ED%88%B4%ED%82%B7-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0-1-%EB%A9%80%ED%8B%B0%EC%8B%9C%EA%B7%B8-ff45488c9a76 

English version: https://klaytn.foundation/using-klaytn-online-toolkit-1-multisig/
