### ISSUE TITLE
Support rosetta-klaytn migration

### ISSUE THREAD

**Issue by jimni1222** [klaytn/project-management#28]
Support rosetta-klaytn migration

**Comment by jimni1222** [comment]
Need to apply https://github.com/klaytn/project-management/issues/29

**Comment by jimni1222** [comment]
During waiting #29, i wanna apply https://github.com/klaytn/rosetta-klaytn/pull/132

**Comment by JayChoi1736** [comment]
fix decimal problem https://github.com/klaytn/rosetta-klaytn/pull/135
fix basefee problem(magma hardfork related) https://github.com/klaytn/rosetta-klaytn/pull/141
