### ISSUE TITLE
Klaytn Online Toolkit Series (medium blog)

### ISSUE THREAD

**Issue by Yeonju-Kim** [klaytn/project-management#30]
Write a series of blogs about How to use Klaytn Online Toolkit. 

Audience: 
- Devs interested in studying Klaytn SDK (caver-js)
- Beginners that want to test Klaytn features

Deadline: Mid of Nov.
Task: refactoring of current online-toolkit
Article:
- Why we need this
- How you can contribute to this

**Comment by skqksh** [comment]
Application part 로 이슈 이관하여, 해당이슈는 닫습니다.
