### ISSUE TITLE
web3modal - klip integration

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#31]

**Comment by Yeonju-Kim** [comment]
Klip integration into web3modal
- Web3modal version2 is an early alpha version. They keep adding features.
- [Klip-web3-provider](https://github.com/klaytn/klip-web3-provider) package has been deployed: derived and modified from @coinbase/wallet-sdk and @walletconnect/qrcode-modal. 
- Supported functions
> 1. send klay
> 2. sign message
> 3. auth 
- Update [klaytn-web3modal](https://github.com/klaytn/klaytn-web3modal) to add Klip support 
- Update [web3modal example page](https://klaytn.github.io/klaytn-online-toolkit/web3modal) of online toolkit
