### ISSUE TITLE
Try to use Reach to check what is good

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#36]
https://docs.reach.sh/tool/#ref-install

Our website —> https://Reach.sh
Short Video explainer —> https://youtu.be/z1nWuxelRpE
Docs —> https://docs.reach.sh/
Overview of a Reach DApp —> https://docs.reach.sh/tut/overview/
Comparison of Reach development with Solidity development —> https://docs.reach.sh/guide/solidity/#guide-solidity

**Comment by edwin082** [comment]
I moved this issue to the [application part - JIRA](https://krustuniverse.atlassian.net/jira/software/projects/CDAP/boards/76/backlog?selectedIssue=CDAP-29)

**Comment by edwin082** [comment]
I moved this issue to the [application part - JIRA](https://krustuniverse.atlassian.net/jira/software/projects/CDAP/boards/76/backlog?selectedIssue=CDAP-29)
