### ISSUE TITLE
klaytn-wagmi implementation

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#41]
- [x] implementation
- [x] CI/CD
- [ ] ~Fix kaikas wallet connector to work with vite-react & next~

**Comment by Yeonju-Kim** [comment]
- @klaytn/wagmi published: https://github.com/klaytn/klaytn-wagmi 
- Original repo provides 4 examples. In Klaytn-wagmi repo, cra and remix examples are modified to work with kaikas wallet, but others are not completed. 
 CRA & remix: Add Klaytn network & kaikas wallet connector.
 vite-react & next: Add klaytn network. Kaikas wallet connector is not working.

**Comment by baerae-colin** [comment]
decided not to fix vite-react & next.
