### ISSUE TITLE
Sample app using Kaikas and metamask together

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#7]
If we use sign function of Metamask, web3.js is used to verify this.

If we use sign function of Kaikas, caver-js is used to verify.

maybe we can use https://github.com/Web3Modal/web3modal

**Comment by Yeonju-Kim** [comment]
-  [@klaytn/web3modal](https://github.com/klaytn/klaytn-web3modal): Updated web3modal code to support Kaikas provider. We have created a PR in web3modal repo, which is still under review. So we temporarily provide @klaytn/web3modal package.
- [@klaytn/kaikas-web3-provider](https://github.com/klaytn/kaikas-web3-provider): To integrate Kaikas Web extension wallet into Dapps that utilize ethereum based APIs, this package provides functions that handle eth namespace APIs using the corresponding klay namespace APIs. 
- Sample App: https://klaytn.github.io/klaytn-online-toolkit/
