### ISSUE TITLE
sample app using nft marketplace

### ISSUE THREAD

**Issue by baerae-colin** [klaytn/project-management#9]
1. deploy ERC-721, ERC-1155, KIP-17, KIP-37 (also consider proxy contract case, ownable)
2. transfer them
3. how to use current marketplaces and open-source marketplaces using wyvern
(OpenSea, Pala square, klaybay, etc)

**Comment by JayChoi1736** [comment]
update caver-js by https://github.com/klaytn/caver-js/pull/711
